name: Changelog
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Changelog Generator from github issues
        id: generate_changelog_file
        uses: heinrichreimer/github-changelog-generator-action@v2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          compareLink: true
          # Get config from .github_changelog_generator file
      - name: create commit
        id: commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: master
          commit_message: "Automatic changelog update"
          file_pattern: "CHANGELOG.md"
